# Configuration for Bugzilla

# Bugzilla server config
server: bugs.meego.com
port: 443
use_ssl: true

# Query URI template
uri: /buglist.cgi?bugidtype=include&columnlist=short_desc%2Cbug_status%2Copendate%2Cresolution%2Cbug_severity%2Cpriority%2Cproduct%2Ccomponent%2Cversion%2Crep_platform&query_format=advanced&ctype=csv

# Proxy server address and port (leave empty if not needed)
proxy_server: 
proxy_port:

# HTTP Basic authentication. You need these only if you must login with HTTP Basic Auth to access Bugzilla
# - i.e. your browsers displays a popup window asking for credentials.
http_username: 
http_password: 
